### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by ajansel** [tjshiu/eatsy#2]
# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
  - Looks good! I would just change `add it` to `add food choices` or something that's a little more descriptive than `it`
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
  - Product listings and comments should both be full CRUD and this should be reflected in the bullets. 
- [x] Estimates how long it will take the code each MVP
  - This still needs to be added. We can discuss this together this afternoon but for now maybe put your estimate and then we can update it when we meet. 
- [x] Each App specific MVP needs the following bullet points are added:
  - The following three bullets above need to be included in the description for each issue that you make. They don't necessarily need to be on this MVP page though: 
    + Adequate styling
    + Smooth, bug-free navigation
    + Seeded with info to demonstrate this feature

- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

# Comments:
- I would probably make your MVPs bigger and bold so they are easier to read. You just need some pounds in front of the numbers, for example: 
   - The two spaces in front of the asterisks are important because they will indent your bullets as well, for better readability. 
```Markdown
### 2. New account creation, login, and guest/demo login (04/04/2018, 2 days)
  * Users can sign up, sign in, log out
  * Users can use a demo login to try the site
  * Users can't use certain features without logging in (Anything with the cart)
```
- Looks good! Once you finish these comment on here to let me know and then I can close the issue!

**Comment by tjshiu** [comment]
Hey AJ! I am mostly done with this! I wasn't sure about the bullet point of the issues. Would you want me to create those later on?

**Comment by ajansel** [comment]
This looks great! Nicely done! Done here (we can talk about the bullets and issues in our 1-on-1)
