### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by ajansel** [tjshiu/eatsy#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
      - My recommendation would be to make all `img_url`s `not null` and instead have an `ensure_img_url` method or a `default`. Right now it's optional for the `users` table. This will ensure that there are not profiles, items, etc. without pictures that would make the site inconsistent. I can explain more on this when we meet as well if you'd like. 
    - [x] unique
      - There should be a unique constraint on the combination of `user_id` and `product_id` via an index so that they don't try to add the same thing to their cart multiple times. See bluebird (link below in comments) for an example. 
    - [x] indexed
      - `session token` should also be indexed since we will search by it so much 
      - `cost` doesn't need to be indexed
      - The foreign keys in `Shopping Cart Items` and `Reviews ` table should be indexed.
    - [x] foreign key
      - Should products `belong_to` a user? If so, you will need a foreign key.  
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - Make sure to do this for each foreign key. See bluebird (link below in comments) for an example.  
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
      - Make sure to add this to all of the table names. Additionally, don't forget to add the header for `users` table.
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
      - Make sure to add this to all of the column names. 
# Comments:
- Make sure that the header `Database Schema` is a header 1, aka has a `#  ` (with the two spaces) in front of it. Then all of the table names should be header 2s, aka `##  ` (with the two spaces) in front of them.
- I would probably change `comments` to `comment`, singular, in your `Reviews` table. 
- [Bluebird Schema](https://github.com/appacademy/bluebird/wiki/schema)

**Comment by tjshiu** [comment]
Complete!

**Comment by ajansel** [comment]
Good work! (Still probably don't need an index on `cost`, but it's up to you). Done here!
