### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by ajansel** [tjshiu/eatsy#4]
# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
- [x] Each route has a description
  - Make sure to add a description to the `homepage` frontend route, what will be displayed there? 
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + ex. probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
    - See my comments for this one
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)
    - Make sure to add this, see bluebird for an example: [Bluebird Routes](https://github.com/appacademy/bluebird/wiki/routes)

# Comments:
- You should only need to nest the `create` routes for reviews API endpoints. Everything else we will already have the product id stored on the frontend. 
- You should also have a `patch` request for reviews, again, it won't need to be nested. 
- Shopping cart won't need to be nested for its API Endpoint either because you will just be getting the `current_users` shopping cart.
- You will need a search controller with API Endpoints that will return the search results

**Comment by tjshiu** [comment]
Complete! However, I wasn't sure about the API endpoints. I would love to talk about it. Also, I wasn't sure how the search controller would work.

**Comment by ajansel** [comment]
Excellent! We can discuss this in more detail 1-on-1 but this is good for now. Done here!
