### ISSUE TITLE
Component Hierarchy with Wireframes

### ISSUE THREAD

**Issue by ajansel** [tjshiu/eatsy#6]
# Component Hierarchy with Wireframes

- [x] All routes listed in the routes wiki page is also listed in the component hierarchy
  - You have the route for products as `/dashboard` but I did not see that in your front end route. Did you maybe mean `/homepage`?
  - You will also need component hierarchy for `signin`, `register`, `create a product`, `update a product`,  `show shopping cart`
  - Product show pages (and maybe index?) will also need to have component hierarchy for the reviews that are left on them
- [x] Each component, if necessary, has route, state, and other components it renders [example](https://github.com/appacademy/bluebird/wiki/component-hierarchy)
  - Products will also need the reviews and images slice of state 
  - ShoppingCart will need the corresponding slice of state 
- [x] Necessary components are wrapped in a container
  - ShoppingCart will probably need a container. As well as any other components you add. 
- [x] Correctly formatted
    - [x] Bullet point hierarchy
    - [x] Component names are displayed with `inline coding text` (backticks)
      - This needs to be updated 

- [x] Wireframes included
      - These need to be added before I can check any of the following:
  - [x] Every component listed in the component hierarchy wiki page has at least one wireframe
  - [x] Every MVPs listed on the MVP wiki page has at least one wireframe
  - [x] Every route listed on the route wiki page has at least one wireframe
  - [x] Contains Containers
  - [x] Contains Lists
  - [x] Contains ListItems
  - [x] Correctly formatted
    - [x] Wireframe images display on the page
    - [x] Every wireframe has a header title

# Comments:
This page will probably require the most work, but it is super important, particularly the wireframes! Let me know if you have any questions!

**Comment by tjshiu** [comment]
Hey AJ I just wanted to let you know I added some wireframes. I still have questions about the component hierarchy. I have a few of them left such as the Users, Shopping Cart, and Sessions. I also realized that I had forgotten to create an edit product form but it should be similar to the create product form. I am hoping you can check off some boxes so that I have a better understanding of what is left!

**Comment by ajansel** [comment]
Excellent! You're good to go!
